### ISSUE TITLE
Improve Documentation

### ISSUE THREAD

**Issue by kmuehlbauer** [openradar/xradar#17]
We now have a minimal documentation, yikes https://docs.openradarscience.org/projects/xradar/
It already looks very nice, but can be improved. 

What's missing list (please extend):

- [x] mention current version string in docs #19 
- [x] mention conda-forge package #19
- [x] update installation guide #19
- [x] update contributing guide #19
- [x] direct links to the current standards #24
- [x] description of the data model (mandatory, optional) #24
- [x] fleshed out description how the importers are working #20 
- [x] showcase of implementation of an example accessor #21
- [x] tutorial on producing PPI plots #28 
- [ ] tutorial on producing RHI plots
- [ ] how to overlay other types of data (ex. model)
- [ ] using hvplot to create interactive plots
- [ ] xmovie example
- [ ] tbc

**Comment by mgrover1** [comment]
Thanks for opening this - I agree here. We can definitely start with these points and continue to expand.

**Comment by mgrover1** [comment]
@kmuehlbauer - here is the repo setup to host sample datasets https://github.com/openradar/open-radar-data . I think we can use this in our examples and such, across these different projects.

**Comment by mgrover1** [comment]
@kmuehlbauer - when I was working on an RHI example, I noticed how helpful it would be if we had azimuth with range as the dimensions instead of time... so one could use the following

```python
radar.sel(azimuth=270, method='nearest')
```

Is this something we can consider? Or does this violate the data model?

**Comment by kmuehlbauer** [comment]
@mgrover1 

Yes, that's what we did in wradlib already. Internally we can do anything we want if only we write out in the correct manner.

Try to open with keyword argument `first_dim="auto"`. This will get either "azimuth" or "elevation" as first dim.

**Comment by kmuehlbauer** [comment]
@egouden We can always improve 😄. But yes, maybe it's better to open dedicated issues nowadays and close this one.
